name: Build AppCSXCAD AppImage

on:
  release:
    types: [published]

jobs:
  build-appcsxcad-appimage:
    runs-on: ubuntu-22.04

    env:
      DEBIAN_FRONTEND: noninteractive
      OPENEMS_DIR: ${{ github.workspace }}/OpenEMS-Project
      APPIMAGE_DIR: ${{ github.workspace }}/appimage
      LINUXDEPLOYQT_DIR: ${{ github.workspace }}/linuxdeployqt-continuous

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'  # This checks out the submodules recursively
        fetch-depth: 0  # ensures full history and tags are available
        path: 'OpenEMS-Project'


    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          git wget build-essential cmake pkg-config \
          libx11-dev x11-apps paraview \
          libhdf5-dev libvtk7-dev libvtk7-qt-dev \
          libboost-all-dev libcgal-dev libtinyxml-dev \
          qtbase5-dev octave liboctave-dev \
          gengetopt help2man groff pod2pdf bison flex libhpdf-dev libtool \
          python3-pip python3-dev python3-tk vim

    - name: Upgrade pip and install Python tools
      run: |
        python3 -m pip install --upgrade pip wheel setuptools==58.2.0 pyproject-toml

    - name: Build fparser
      working-directory: ${{ env.OPENEMS_DIR }}/fparser
      run: |
        cmake .
        make -j$(nproc)
        sudo make install

    - name: Build CSXCAD
      working-directory: ${{ env.OPENEMS_DIR }}/CSXCAD
      run: |
        cmake .
        make -j$(nproc)
        sudo make install

    - name: Build QCSXCAD
      working-directory: ${{ env.OPENEMS_DIR }}/QCSXCAD
      run: |
        cmake .
        make -j$(nproc)
        sudo make install

    - name: Build AppCSXCAD
      working-directory: ${{ env.OPENEMS_DIR }}/AppCSXCAD
      run: |
        cmake -DCMAKE_INSTALL_PREFIX=${{ env.OPENEMS_DIR }}/AppCSXCAD/local .
        make -j$(nproc)
        sudo make install

    - name: Download and extract linuxdeployqt
      working-directory: ${{ github.workspace }}
      run: |
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt-continuous-x86_64.AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage --appimage-extract
        mv squashfs-root linuxdeployqt-continuous

    - name: Create build directory
      working-directory: ${{ github.workspace }}
      run: mkdir -p ${{ env.APPIMAGE_DIR }}

    - name: Prepare AppImage structure
      working-directory: ${{ env.APPIMAGE_DIR }}
      run: |
        mkdir -p local/bin
        cp ${{ env.OPENEMS_DIR }}/AppCSXCAD/local/bin/AppCSXCAD local/bin
        cp ${{ env.OPENEMS_DIR }}/assets/appcsxcad.png ./

        echo "[Desktop Entry]
        Type=Application
        Name=AppCSXCAD
        Exec=AppRun %F
        Icon=appcsxcad
        Comment=View and edit OpenEMS Geometries
        Terminal=true
        Categories=Education;Science;" > default.desktop

    - name: Bundle AppImage
      working-directory: ${{ env.APPIMAGE_DIR }}
      run: |
        "${LINUXDEPLOYQT_DIR}/AppRun" local/bin/AppCSXCAD \
          -appimage -bundle-non-qt-libs -verbose=2

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.APPIMAGE_DIR }}/AppCSXCAD*.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
